config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :activities

  resource :sessions, only: [:new, :destroy]
  resources :chats, only: [:show, :edit, :update, :destroy]

  resources :books do
    resources :chats, only: [:index, :new, :create]
  end

  resources :sessions
  resources :users

end

app/models/book.rb
class Book < ActiveRecord::Base
  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
    where("content ILIKE ?", "%#{search}%")
  end
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :user
  has_many :chats
  has_many :user_books
  has_many :users, through: :user_books

  validates :title, uniqueness: true

end

app/models/chat.rb
class Chat < ActiveRecord::Base

  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :book
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

  
end

app/models/goodreads_api.rb
class GoodreadsAPI
  def self.client
    Goodreads::Client.new(:api_key => 'X9YtyhHcbo8epOwkayEtEA', :api_secret => 'hi0fQvg8rbw2fufhHYOlsreqb1oKq0iU29zXaXVrMec')
  end

  def self.book_by_title(title)
    client.book_by_title(title)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :image, styles: { thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  has_secure_password
  
  has_many :user_books
  has_many :chats
  has_many :books, through: :user_books
  has_many :ActivitiesController
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  include PublicActivity::Model
  belongs_to :user
  belongs_to :book
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = PublicActivity::Activity.order("created_at desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def index
        @books = Book.search(params[:search])
  end

  include PublicActivity::StoreController


  protect_from_forgery with: :exception

  helper_method :current_user


  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) #wont go into the database if we have the correct user
  end

  def require_logged_in
    return true if current_user

    redirect_to root_path
    return false
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in


  # GET /books
  # GET /books.json

def index
  @books = Book.all
end

  # GET /books/1
  # GET /books/1.json
  def show
  @book = Book.find(params[:id])
  @chat = Chat.new
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # Book /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:user_id, :title, :author, :description)
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:index, :create, :new]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.book = @book


    respond_to do |format|
      if @chat.save
        format.html { redirect_to book_path(@chat.book) }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:comment, :book_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

def destroy
  session[:user_id] = nil
  @current_user = nil
  redirect_to root_path
  return
end

def index
end

  def create
    @user = User.
    find_by(username: params[:username]).
    try(:authenticate, params[:password])

    if @user
      session[:user_id] = @user.id
      redirect_to books_path
    else
      render action: 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

   def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Created user"
    else
      render action: 'new'
    end
  end

  def index
    # @user = User.find(params[:id])
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    else
      # render action: 'new'
    end
  end

  private

  def user_params
    params.
    require(:user).
    permit(:username, :password, :password_confirmation, :name, :bio, :image)
  end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<h1> Friends Activities </h1>

<% @activities.each do |activity| %>
<div class="activity">
  <%= link_to activity.owner.username, activity.owner if activity.owner %>
  <%= render_activity activity %>
</div>

<% end %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class='head'>
<h2>Trending Books</h2>
</div>
<table>

  <tbody>
    <% @books.each do |book| %>

      <tr>
      <div class="grid">
      <% if book.url %>
       <%= link_to image_tag(book.url), book %>
        <% end %>
      </div>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
  <%= image_tag(@book.url) %>

<p>
  <strong>Title:</strong>
  <%= @book.title  %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description.html_safe %>
</p>

<br>
<br>

 <div class="chat">
<% @book.chats.each do |chat| %>
<p>
  <%= chat.comment %>
  <br>


  <%= link_to chat.user.username, user_path(chat.user)  %> |
  Added on: <%= localize(chat.created_at, :format => :long) %>

<br>
<br>

</p>
<% end %>

<div class="chat">
<h3>Join the Conversation...</h3>


<%= render 'chats/form' %>
<%# link_to 'Back', books_path %>

</div>

app/views/chats/_form.html.erb
<%= form_for([@book, @chat]) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit :Chat %>

  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chats</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.comment %></td>
        <td><%= chat.book %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Show Page', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @chat.comment %>
</p>

<p>
  <strong>Book:</strong>
  <%= @chat.book %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', book_path %>

app/views/layouts/_activity.html.erb
<%= render_activities(@activities, layout: :activity) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Libro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Roboto+Slab:300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>





<nav>
   <div class="hamburger-shell">
      <div class="hamb top"></div>
      <div class="hamb middle"></div>
      <div class="menu-name">MENU</div>
   </div>
   <ul id="menu">
      <li><%= link_to 'Explore', books_path, {:style=>'color: #BCE7FD;',  :class => "css_class"} %></li>
      <li><% link_to 'Sign Up', new_user_path, {:style=>'color: #BCE7FD;',  :class => "css_class"} %></li>
      <li><%= link_to_unless(@current_user.nil?, "Profile", user_path(current_user), {:style=>'color:#BCE7FD;', :class => "css_class"}) %></li>
      <li><%= link_to 'Activity', activities_path, {:style=>'color:#BCE7FD;'} %></li>
     <li> <%= link_to 'Logout', sessions_path, {:style=>'color:#BCE7FD;'} %></li>
   </ul>

 </nav>


 <body>


 <% unless @current_user.nil? %>

   <header class='header-container'>
     <h1 class='libro-logo'>L I B R O</h1>
     <div class='container'>
      <div class='search-container'>
        <input placeholder=' search' type='text'>
        <a class='button'>
         <i class="fa fa-search"></i>
        </a>
      </div>
    </div>
   </header>

   <% end %>

<%= yield %>


</body>
</html>

app/views/public_activity/book/_create.html.erb
added comment <%= link_to image_tag(activity.trackable.url) ,
activity.trackable.url %>

app/views/public_activity/book/_update.html.erb
added comment <%= link_to activity.trackable.book.title,
activity.trackable.book.title %>

app/views/public_activity/chat/_create.html.erb
added comment <%= link_to activity.trackable.book.title,
activity.trackable.book.title %>

app/views/public_activity/chat/_update.html.erb
added comment <%= link_to activity.trackable.book.title,
activity.trackable.book.title %>

app/views/public_activity/user/_create.html.erb
added comment

<% if activity.trackable %>
<%= link_to activity.trackable(@book), activity.trackable(@book) %>
<% else %>
which has been removed
<% end %>

app/views/users/new.html.erb
<div class="sign-up-box">

<div class="name">
  <h1>L I B R O</h1>
  <h2>Find your book, join the discussion.<h2>

</div>

  <div class="form">
    <h3>Sign Up</h3>
    <%= form_for @user, html: { multipart: true } do |f| %>

      <p>
       <%= f.text_field :username, placeholder: "Username", class: 'form' %>
      </p>

      <p>
       <%= f.password_field :password, placeholder: "Password", class: 'form' %>
      </p>

      <p>
       <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form' %>
      </p>

      <p>
         <%= f.text_field :name, placeholder: "Name", class: 'form' %>
      </p>

      <p>
        <%= f.file_field :image, placeholder:"Upload a Picture", class: 'form' %>
      </p>

      <p>
        <%= f.text_field :bio, placeholder: "Bio", class: 'form' %>
      </p>

      <p>
        <%= f.submit "Sign Up", class: 'animated'  %>
      </p>

        <% end %>

  </div>

</div>

app/views/users/show.html.erb
<h1>My Profile</h1>


<div class="photo">
<%= image_tag @user.image.url(:thumb), class: "profile_pic" %>
</div>

<br>

<div class="name">
 Name: <%= @user.name %>
 </div>

<br>
<div class="username">
Username: <%= @user.username %>
</div>

<br>

<div class="bio">
Bio: <%= @user.bio %>
  </div>
 </div>